# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17f127225ba5b03817171da6bbac153c55629899c4307f111982603a93063d388e0034d1b7a05f83c0a5f5996d2709070d5057b14df205b317c055e32d7d7b9

test:
  secret_key_base: 484ab074f6ab70ce851d0b1c61bbe28e4857c1c5144e0adf6ce66c16d3cb70192d98318166e8a1dd22e3e3a53fa9f9a9b2f81f837e7df9a31c5643db9c2ac383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 84f3b2163cab93ca2253842b5f19461374cad5fe189169629debf2c1d1d30b1249c39b95e805981476252ac560e6c2833e4477e7fb3c274ee0532403cf0dd07a
